services:
  ddt-erp-db:
    container_name: ddt-erp-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erp
    ports:
      - "5433:5432"
    volumes:
      - ddt_erp_postgres_data:/var/lib/postgresql/data

volumes:
  ddt_erp_postgres_data:
