import { WooOrder, WooProduct, WooSystemStatus } from "./types";

export const mockWooSystemStatus: WooSystemStatus = {
  environment: {
    home_url: "https://northstar-demo.shop",
    version: "9.0.0",
  },
  settings: {
    currency: "PKR",
  },
};

export const mockWooProducts: WooProduct[] = [
  {
    id: 5101,
    name: "ProBook X15",
    sku: "PRO-X15",
    regular_price: "1299",
    sale_price: "1249",
    stock_quantity: 18,
    manage_stock: true,
    stock_status: "instock",
    categories: [{ id: 10, name: "Electronics" }],
    images: [{ id: 1, src: "https://images.demo.local/woo-probook-x15.jpg" }],
  },
  {
    id: 5102,
    name: "Ergo Wireless Mouse",
    sku: "ACC-M01",
    regular_price: "49.99",
    sale_price: "44.99",
    stock_quantity: 57,
    manage_stock: true,
    stock_status: "instock",
    categories: [{ id: 11, name: "Accessories" }],
    images: [{ id: 2, src: "https://images.demo.local/woo-ergo-mouse.jpg" }],
  },
  {
    id: 5103,
    name: "USB-C to HDMI 2m",
    sku: "CBL-U2H",
    regular_price: "24",
    sale_price: "",
    stock_quantity: 130,
    manage_stock: true,
    stock_status: "instock",
    categories: [{ id: 12, name: "Cables" }],
    images: [{ id: 3, src: "https://images.demo.local/woo-cable.jpg" }],
  },
];

export const mockWooOrders: WooOrder[] = [
  {
    id: 9101,
    number: "9101",
    status: "completed",
    date_created: new Date().toISOString(),
    subtotal: "1299",
    total_discount: "50",
    shipping_total: "250",
    total: "1499",
    payment_method: "cod",
    payment_method_title: "Cash on Delivery",
    billing: {
      first_name: "Hamza",
      last_name: "Ali",
      email: "hamza.ali@example.pk",
      phone: "+92-300-5551234",
      address_1: "Gulberg III",
      city: "Lahore",
      country: "PK",
    },
    line_items: [
      {
        id: 3001,
        product_id: 5101,
        sku: "PRO-X15",
        name: "ProBook X15",
        quantity: 1,
        price: 1249,
        subtotal: "1299",
        total: "1249",
      },
    ],
  },
  {
    id: 9102,
    number: "9102",
    status: "processing",
    date_created: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    subtotal: "113.98",
    total_discount: "0",
    shipping_total: "180",
    total: "293.98",
    payment_method: "bacs",
    payment_method_title: "Bank Transfer",
    billing: {
      first_name: "Sara",
      last_name: "Khan",
      email: "sara.khan@example.pk",
      phone: "+92-321-9988776",
      address_1: "Clifton Block 5",
      city: "Karachi",
      country: "PK",
    },
    line_items: [
      {
        id: 3002,
        product_id: 5102,
        sku: "ACC-M01",
        name: "Ergo Wireless Mouse",
        quantity: 2,
        price: 44.99,
        subtotal: "99.98",
        total: "89.98",
      },
      {
        id: 3003,
        product_id: 5103,
        sku: "CBL-U2H",
        name: "USB-C to HDMI 2m",
        quantity: 1,
        price: 24,
        subtotal: "24",
        total: "24",
      },
    ],
  },
];
