import { z } from "zod";

import type { IntegrationActionDefinition } from "./types";

const recordPayloadSchema = z.object({
  recordId: z.string().min(1).optional(),
  recordName: z.string().min(1).optional(),
  content: z.string().min(1).optional(),
});

export const INTEGRATION_ACTIONS: IntegrationActionDefinition[] = [
  {
    key: "calendar.check_availability",
    name: "Check Availability",
    description: "Read available calendar slots from a connected provider.",
    capability: "calendar.read",
    inputSchema: z.object({ startAt: z.string().datetime(), endAt: z.string().datetime() }),
    outputSchema: z.object({ slots: z.array(z.string()) }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "low",
    confirmationRequired: false,
    approvalPolicy: "none",
    idempotencyRequired: false,
    auditRequired: true,
    timeoutMs: 15_000,
    retryPolicy: "standard_read",
  },
  {
    key: "calendar.create_event",
    name: "Create Event",
    description: "Create a new calendar event.",
    capability: "calendar.write",
    inputSchema: z.object({
      title: z.string().min(1),
      startAt: z.string().datetime(),
      endAt: z.string().datetime(),
    }),
    outputSchema: z.object({ eventId: z.string() }),
    requiredIndustryCapabilities: ["supports_future_bookings"],
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "moderate",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 20_000,
    retryPolicy: "standard_write",
  },
  {
    key: "calendar.reschedule_event",
    name: "Reschedule Event",
    description: "Reschedule an existing calendar event.",
    capability: "calendar.write",
    inputSchema: z.object({
      eventId: z.string().min(1),
      startAt: z.string().datetime(),
      endAt: z.string().datetime(),
    }),
    outputSchema: z.object({ eventId: z.string() }),
    requiredIndustryCapabilities: ["supports_future_bookings"],
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "moderate",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 20_000,
    retryPolicy: "standard_write",
  },
  {
    key: "calendar.cancel_event",
    name: "Cancel Event",
    description: "Cancel a calendar event through a connected provider.",
    capability: "calendar.write",
    inputSchema: z.object({ eventId: z.string().min(1) }),
    outputSchema: z.object({ eventId: z.string() }),
    requiredIndustryCapabilities: ["supports_future_bookings"],
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "moderate",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 15_000,
    retryPolicy: "standard_write",
  },
  {
    key: "contacts.search",
    name: "Search Contacts",
    description: "Search contacts in an external provider.",
    capability: "contacts.read",
    inputSchema: z.object({ query: z.string().min(1) }),
    outputSchema: z.object({ matches: z.array(z.record(z.string(), z.unknown())) }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "low",
    confirmationRequired: false,
    approvalPolicy: "none",
    idempotencyRequired: false,
    auditRequired: true,
    timeoutMs: 12_000,
    retryPolicy: "standard_read",
  },
  {
    key: "contacts.create",
    name: "Create Contact",
    description: "Create a contact in an external provider.",
    capability: "contacts.write",
    inputSchema: z.object({
      name: z.string().min(1),
      phone: z.string().optional(),
      email: z.string().optional(),
      company: z.string().optional(),
    }),
    outputSchema: z.object({ contactId: z.string() }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "moderate",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 15_000,
    retryPolicy: "standard_write",
  },
  {
    key: "contacts.update",
    name: "Update Contact",
    description: "Update an existing contact in an external provider.",
    capability: "contacts.write",
    inputSchema: z.object({
      contactId: z.string().min(1),
      name: z.string().optional(),
      phone: z.string().optional(),
      email: z.string().optional(),
      company: z.string().optional(),
    }),
    outputSchema: z.object({ contactId: z.string() }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "moderate",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 15_000,
    retryPolicy: "standard_write",
  },
  {
    key: "email.create_draft",
    name: "Create Draft",
    description: "Create a draft email in a connected mailbox.",
    capability: "email.write",
    inputSchema: z.object({
      to: z.array(z.string().min(3)).min(1),
      subject: z.string().min(1),
      body: z.string().min(1),
    }),
    outputSchema: z.object({ messageId: z.string() }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "moderate",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 20_000,
    retryPolicy: "standard_write",
  },
  {
    key: "email.send",
    name: "Send Email",
    description: "Send an email through a connected mailbox.",
    capability: "email.write",
    inputSchema: z.object({
      to: z.array(z.string().min(3)).min(1),
      subject: z.string().min(1),
      body: z.string().min(1),
    }),
    outputSchema: z.object({ messageId: z.string() }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "high",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 20_000,
    retryPolicy: "standard_write",
  },
  {
    key: "email.reply",
    name: "Reply To Email",
    description: "Reply to an existing email thread.",
    capability: "email.write",
    inputSchema: z.object({
      threadId: z.string().min(1),
      body: z.string().min(1),
    }),
    outputSchema: z.object({ messageId: z.string() }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "high",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 20_000,
    retryPolicy: "standard_write",
  },
  {
    key: "data.read_rows",
    name: "Read Rows",
    description: "Read rows from a connected data source.",
    capability: "data.read",
    inputSchema: z.object({
      resourceId: z.string().min(1).optional(),
      worksheet: z.string().optional(),
      limit: z.number().int().positive().max(500).default(50),
    }),
    outputSchema: z.object({ rows: z.array(z.record(z.string(), z.unknown())) }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "low",
    confirmationRequired: false,
    approvalPolicy: "none",
    idempotencyRequired: false,
    auditRequired: true,
    timeoutMs: 15_000,
    retryPolicy: "standard_read",
  },
  {
    key: "data.append_row",
    name: "Append Row",
    description: "Append a row to a connected spreadsheet or dataset.",
    capability: "data.write",
    inputSchema: z.object({
      resourceId: z.string().min(1).optional(),
      row: z.record(z.string(), z.unknown()),
    }),
    outputSchema: z.object({ rowId: z.string() }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "moderate",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 15_000,
    retryPolicy: "standard_write",
  },
  {
    key: "data.update_row",
    name: "Update Row",
    description: "Update a row in a connected spreadsheet or dataset.",
    capability: "data.write",
    inputSchema: z.object({
      resourceId: z.string().min(1).optional(),
      rowId: z.string().min(1),
      row: z.record(z.string(), z.unknown()),
    }),
    outputSchema: z.object({ rowId: z.string() }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "moderate",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 15_000,
    retryPolicy: "standard_write",
  },
  {
    key: "crm.create_lead",
    name: "Create Lead",
    description: "Create a CRM lead in a connected provider.",
    capability: "crm.write",
    inputSchema: z.object({ name: z.string().min(1), notes: z.string().optional() }),
    outputSchema: z.object({ leadId: z.string() }),
    allowedRequestSources: ["user", "voice_agent", "worker"],
    sensitivity: "moderate",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 20_000,
    retryPolicy: "standard_write",
  },
  {
    key: "developer.trigger_webhook",
    name: "Trigger Webhook",
    description: "Trigger a configured developer webhook.",
    capability: "developer.webhook",
    inputSchema: z.object({ eventKey: z.string().min(1), payload: z.record(z.string(), z.unknown()) }),
    outputSchema: z.object({ deliveryId: z.string() }),
    allowedRequestSources: ["user", "worker", "system"],
    sensitivity: "high",
    confirmationRequired: true,
    approvalPolicy: "always",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 15_000,
    retryPolicy: "webhook_delivery",
  },
  {
    key: "developer.execute_rest_operation",
    name: "Execute REST Operation",
    description: "Execute an approved outbound REST operation.",
    capability: "developer.rest",
    inputSchema: z.object({ method: z.string().min(1), path: z.string().min(1) }),
    outputSchema: z.object({ statusCode: z.number().int() }),
    allowedRequestSources: ["user", "system"],
    sensitivity: "restricted",
    confirmationRequired: true,
    approvalPolicy: "always",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 20_000,
    retryPolicy: "none",
  },
  {
    key: "internal_test.read_record",
    name: "Read Test Record",
    description: "Read a mocked record from the internal integration provider.",
    capability: "internal_test.read",
    inputSchema: recordPayloadSchema,
    outputSchema: z.object({
      recordId: z.string(),
      recordName: z.string(),
      resourceId: z.string(),
    }),
    allowedRequestSources: ["user", "voice_agent", "worker", "system"],
    sensitivity: "low",
    confirmationRequired: false,
    approvalPolicy: "none",
    idempotencyRequired: false,
    auditRequired: true,
    timeoutMs: 8_000,
    retryPolicy: "standard_read",
  },
  {
    key: "internal_test.create_record",
    name: "Create Test Record",
    description: "Create a mocked record through the internal integration provider.",
    capability: "internal_test.write",
    inputSchema: z.object({
      recordName: z.string().min(1),
      content: z.string().min(1),
      simulateApproval: z.boolean().default(false),
    }),
    outputSchema: z.object({
      recordId: z.string(),
      created: z.boolean(),
    }),
    allowedRequestSources: ["user", "voice_agent", "worker", "system"],
    sensitivity: "high",
    confirmationRequired: true,
    approvalPolicy: "tenant_configurable",
    idempotencyRequired: true,
    auditRequired: true,
    timeoutMs: 8_000,
    retryPolicy: "standard_write",
  },
];

const actionMap = new Map(INTEGRATION_ACTIONS.map((action) => [action.key, action]));

export function getIntegrationActionDefinition(actionKey: string) {
  return actionMap.get(actionKey) || null;
}
